# Generated by Django 5.1.4 on 2024-12-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_per',
            new_name='price_per_day',
        ),
    ]
