# Generated by Django 5.1.4 on 2024-12-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="landlord",
            new_name="landlord",
        ),
    ]
