# Generated by Django 5.1.4 on 2024-12-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='favorite',
            new_name='favorited',
        ),
    ]
